#' @title Aggregate abundance samples
#' @description Takes  site level samples generated by `site.simulate` and aggregates
#' the abundance by the specified `ag.var` argument
#' @param object A tibble produced by `site.simulate()`
#' @param ag.var A column variabe in `object` that is used to form the aggregation
#' @import rlang dplyr
#' @author Devin S. Johnson
#' @export

ag.abundance = function(object, ag.var){
  ag.var=rlang::enquo(ag.var)
  object %>% dplyr::group_by(!!ag.var) %>%
    summarize(
      post.sample = Reduce('+', post.sample) %>% list(),
      post.sample.real = Reduce('+', post.sample.real) %>% list(),
      obs.times = purrr::map(data, ~{.$time}) %>% unlist() %>% unique() %>% list()
    ) %>% ungroup() -> object
  return(object)
}

#' @title Summarize aggregated abundance samples
#' @description Takes aggregated abundance samples and summarizes them for plotting, etc.
#' @param object A tibble produced by `ag.abundance()`
#' @import dplyr coda
#' @author Devin S. Johnson
#' @export

ag.summ = function(object, ci.prob=0.95){
  max.time = object$post.sample %>% purrr::map_int(~{nrow(.x)-1L}) %>% .[1]
  object=object %>% mutate(
    summary = pmap(list(post.sample, post.sample.real, obs.times),
      .f = function(smp,smp.r,times){
        summ = data.frame(
          type = "prediction",
          time=c(0:max.time),
          estimate = apply(smp, 1, median) %>% round(),
          se.est = apply(smp, 1, sd) %>% round()
        ) %>% cbind(
          coda::mcmc(t(smp)) %>% HPDinterval(prob=ci.prob) %>% round() %>% as.data.frame
        )
        summ.real = data.frame(
          type = "realized",
          time=c(0:max.time),
          estimate = apply(smp.r, 1, median) %>% round(),
          se.est = apply(smp.r, 1, sd) %>% round()
        ) %>% cbind(
          coda::mcmc(t(smp.r)) %>% HPDinterval(prob=ci.prob) %>% round() %>% as.data.frame
        ) %>% filter(time%in%times)
        out = rbind(summ, summ.real) %>% as.tibble() %>%
          rename(ci.lower=lower, ci.upper=upper)
        return(out)
      }
    )
  )
  object=object %>% select(-post.sample, -post.sample.real, -obs.times) %>% unnest()
  return(object)
}
